title: Jelle Dekkers
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
url: https://adriaanjelle.nl

color_scheme: custom
favicon_ico: "/assets/images/favicon.png"
# logo: "/assets/images/logo.png"

search_enabled: false
heading_anchors: false

# aux_links:
  # Home: https://adriaanjelle.nl
  # Blog: https://adriaanjelle.nl/blog/700-nas-build
  # Rainmeter: https://adriaanjelle.nl/rainmeter
  
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"