title: Jelle Dekkers
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
url: https://adriaanjelle.nl

color_scheme: custom
favicon_ico: "/assets/images/favicon.png"

search_enabled: false
heading_anchors: false

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"